#!/usr/bin/env bash
set -e

# Ensure the installer is run with sudo/root privileges
if [ "$EUID" -ne 0 ]; then
  echo "==> [Error] Please run this installer with sudo: sudo bash install.sh"
  exit 1
fi

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
RESET='\033[0m'

info() { echo -e "${BLUE}==>${RESET} $1"; }
success() { echo -e "${GREEN}==>${RESET} $1"; }
warn() { echo -e "${YELLOW}==> [Warning]${RESET} $1"; }
err() { echo -e "${RED}==> [Error]${RESET} $1"; }

info "Initializing Nixonator root-protected bootstrap installation..."

CONFIG_DIR="/etc/nixos"
mkdir -p "$CONFIG_DIR"
cd "$CONFIG_DIR"

# Explicitly read from /dev/tty so piping via curl | sudo sh works smoothly
read -p "Enter your dotfiles git repository URL: " REPO_URL </dev/tty
if [ -z "$REPO_URL" ]; then
  err "Repository URL cannot be empty!"
  exit 1
fi

# --- Trust model warning (intentional design tradeoff, surfaced for awareness) ---
# This installer runs as root and writes directly to $CONFIG_DIR. It manages,
# modifies, and can fully wipe (--nuke) that directory, and the Nixonator
# nixonator.nix module executes arbitrary shell as root at rebuild time.
warn "Running as root. This installer manages and can fully wipe (--nuke) $CONFIG_DIR."
warn "Configured repository: $REPO_URL"
warn "Anything $REPO_URL and the Nixonator module resolve to at rebuild time runs as root and can control this machine."
warn "Only use repositories, remotes, and modules you fully trust. Review sources before proceeding."

# Clone repository directly if .git doesn't exist
if [ ! -d ".git" ]; then
  if [ -z "$(ls -A "$CONFIG_DIR")" ]; then
    info "Cloning repository from $REPO_URL..."
    git clone "$REPO_URL" .
  else
    info "Directory is not empty. Initializing remote connection..."
    git init -b main
    git remote add origin "$REPO_URL"
    git fetch origin main
    git checkout -b main origin/main 2>/dev/null || true
  fi
else
  git remote set-url origin "$REPO_URL" 2>/dev/null || git remote add origin "$REPO_URL"
  info "Pulling latest changes from remote..."
  git pull origin main || true
fi

# Ensure modules/nixonator directory exists
MODULE_DIR="$CONFIG_DIR/modules/nixonator"
mkdir -p "$MODULE_DIR"

# Automatically fetch nixonator.nix if missing locally
if [ ! -f "$MODULE_DIR/nixonator.nix" ]; then
  info "Fetching nixonator.nix module..."
  curl -sL "https://raw.githubusercontent.com/usr40k/nixonator/main/modules/nixonator/nixonator.nix" -o "$MODULE_DIR/nixonator.nix" 2>/dev/null || true

  # Fallback if the remote fetch failed
  if [ ! -s "$MODULE_DIR/nixonator.nix" ]; then
    warn "Could not fetch remote nixonator.nix."
    info "Generating a minimal fallback module so the system can still be managed..."
    cat > "$MODULE_DIR/nixonator.nix" <<'NIXONATOR_FALLBACK'
# Generated by install.sh because the remote Nixonator module (https://raw.githubusercontent.com/usr40k/nixonator/main/modules/nixonator/nixonator.nix)
# could not be fetched. This is only a placeholder so the module path still exists.
# Replace it with the real module afterward by running:  sudo nixos-rebuild --nixonator-update
{ config, lib, pkgs, ... }:

let
  # Passthrough wrapper that also handles --nixonator-update so the full
  # module can be fetched even while this placeholder is still installed.
  fallbackRebuild = pkgs.writeShellScriptBin "nixos-rebuild" ''
    TARGET="/etc/nixos/modules/nixonator/nixonator.nix"
    URL="https://raw.githubusercontent.com/usr40k/nixonator/main/modules/nixonator/nixonator.nix"

    if [ "''${1:-}" = "--nixonator-update" ]; then
      echo "Nixonator: fetching the full module from remote..."
      if curl -fsSL "$URL" -o "$TARGET"; then
        echo "Nixonator: full module installed to $TARGET."
        echo "Re-run your rebuild (e.g. 'sudo nixos-rebuild switch') to activate it."
        exit 0
      else
        echo "Nixonator: failed to fetch remote nixonator.nix." >&2
        exit 1
      fi
    fi

    exec ${pkgs.nixos-rebuild}/bin/nixos-rebuild "$@"
  '';
in
{
  environment.systemPackages = [ fallbackRebuild ];
}
NIXONATOR_FALLBACK
    warn "Wrote fallback nixonator.nix to $MODULE_DIR/nixonator.nix."
    warn "Fetch the real module later with: sudo nixos-rebuild --nixonator-update"
  else
    success "Fetched nixonator.nix module."
  fi
fi

# Generate configuration file if it doesn't exist
if [ ! -f "$MODULE_DIR/nixonator.conf" ]; then
  info "Generating nixonator.conf..."
  read -p "Enter your Git User Name: " GIT_NAME </dev/tty
  read -p "Enter your Git User Email: " GIT_EMAIL </dev/tty

  cat <<EOF > "$MODULE_DIR/nixonator.conf"
# Nixonator Configuration
REPO_URL="$REPO_URL"
GIT_BRANCH="main"
SSH_KEY_PATH="/root/.ssh/id_ed25519"

# Git Identity & GPG Signing Configuration
GIT_USER_NAME="$GIT_NAME"
GIT_USER_EMAIL="$GIT_EMAIL"
GPG_SIGNING_KEY=""

# Automatic Garbage Collection Options
AUTO_GC="true"
GC_DAYS="7"

# Pre-rebuild summary & confirmation
PRE_INSTALL_SUMMARY="true"
CONFIRM_UPDATE="false"

# Output style
PRETTY_GIT_SUMMARY="true"
SHOW_GC_STATS="true"

# How to handle newly created (untracked) files in $CONFIG_DIR:
#   ask    - prompt per file: [y]es/[n]o/[a]lways
#   always - stage every untracked file automatically
#   never  - never stage untracked files automatically
PROMPT_UNTRACKED="ask"
EOF
  success "Created $MODULE_DIR/nixonator.conf"
fi

# Ensure git trusts the root-owned repository directory
git config --system --add safe.directory "$CONFIG_DIR" 2>/dev/null || git config --global --add safe.directory "$CONFIG_DIR" 2>/dev/null || true

success "Nixonator root-protected bootstrap complete!"
echo ""
echo "======================================================================"
echo "🎯 NEXT STEPS TO ACTIVATE NIXONATOR:"
echo "======================================================================"
echo "1. Ensure Flakes are enabled in your system (e.g. in configuration.nix):"
echo "   nix.settings.experimental-features = [ \"nix-command\" \"flakes\" ];"
echo ""
echo "2. Import the Nixonator module inside your host configuration file"
echo "   (e.g., hosts/\$(hostname)/default.nix or configuration.nix):"
echo "   imports = [ ../../modules/nixonator/nixonator.nix ];"
echo ""
echo "3. Ensure your flake outputs map to your hostname:"
echo "   outputs = { self, nixpkgs, ... }@inputs: {"
echo "     nixosConfigurations.$(hostname) = nixpkgs.lib.nixosSystem {"
echo "       modules = [ ./hosts/$(hostname)/configuration.nix ];"
echo "     };"
echo "   };"
echo ""
echo "4. Run your first managed rebuild:"
echo "   sudo nixos-rebuild switch"
echo "======================================================================"
